/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: 'rgb(var(--bg-primary) / <alpha-value>)',
          surface: 'rgb(var(--bg-surface) / <alpha-value>)',
          surface2: 'rgb(var(--bg-surface2) / <alpha-value>)',
          surface3: 'rgb(var(--bg-surface3) / <alpha-value>)',
          surface4: 'rgb(var(--bg-surface4) / <alpha-value>)',
        },
        text: {
          primary: 'rgb(var(--text-primary) / <alpha-value>)',
          secondary: 'rgb(var(--text-secondary) / <alpha-value>)',
          muted: 'rgb(var(--text-muted) / <alpha-value>)',
        },
        border: {
          DEFAULT: 'rgb(var(--border-color) / <alpha-value>)',
          subtle: 'rgb(var(--border-subtle) / <alpha-value>)',
          strong: 'rgb(var(--border-strong) / <alpha-value>)',
        },
        user: '#171717',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--accent-hover) / <alpha-value>)',
        'accent-subtle': 'var(--accent-subtle)',
        deepseek: '#f97316',
        'deepseek-reasoner': '#ea580c',
        glm: '#10b981',
        mimo: '#f59e0b',
        qwen: '#8b5cf6',
        success: '#10b981',
        warning: '#f59e0b',
        error: '#ef4444',
        link: '#0066ff',
        'icon-bar': 'var(--icon-bar-bg)',
        'sidebar-hover': 'var(--sidebar-hover)',
        'sidebar-active': 'var(--sidebar-active)',
      },
      fontFamily: {
        sans: ['Noto Sans SC', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'title': 'var(--font-size-xl, 19px)',
        'subtitle': 'var(--font-size-md, 15px)',
        'body': 'var(--chat-message-font-size, 14px)',
        'caption': 'var(--font-size-sm, 12px)',
        'timestamp': 'var(--chat-timestamp-font-size, 10px)',
      },
      spacing: {
        'message-padding': '10px 14px',
        'message-gap': '12px',
        'section-padding': '16px 22px',
        'panel-padding': '20px 18px',
      },
      borderRadius: {
        'card': '12px',
        'message': '18px',
        'button': '10px',
      },
      animation: {
        'message-in': 'messageIn 300ms ease',
        'typing-dot': 'typingDot 1400ms ease infinite',
        'fade-in': 'fadeIn 150ms ease-out forwards',
        'fade-out': 'fadeOut 150ms ease-in forwards',
        'slide-in': 'slideIn 200ms ease',
        'slide-in-left': 'slideInLeft 300ms cubic-bezier(0.0, 0.0, 0.2, 1) forwards',
        'slide-in-right': 'slideInRight 300ms cubic-bezier(0.0, 0.0, 0.2, 1) forwards',
        'slide-in-top': 'slideInTop 300ms cubic-bezier(0.0, 0.0, 0.2, 1) forwards',
        'slide-in-bottom': 'slideInBottom 300ms cubic-bezier(0.0, 0.0, 0.2, 1) forwards',
        'slide-out-left': 'slideOutLeft 300ms cubic-bezier(0.4, 0.0, 1, 1) forwards',
        'slide-out-right': 'slideOutRight 300ms cubic-bezier(0.4, 0.0, 1, 1) forwards',
        'slide-out-top': 'slideOutTop 300ms cubic-bezier(0.4, 0.0, 1, 1) forwards',
        'slide-out-bottom': 'slideOutBottom 300ms cubic-bezier(0.4, 0.0, 1, 1) forwards',
        'scale-in': 'scaleIn 150ms cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards',
        'scale-out': 'scaleOut 150ms cubic-bezier(0.4, 0.0, 1, 1) forwards',
        'bounce-in': 'bounceIn 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55) forwards',
        'bounce': 'bounce 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'shimmer': 'shimmer 1.5s linear infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'typing-dot-anim': 'typingDot 1s ease-in-out infinite',
        'ripple': 'ripple 500ms cubic-bezier(0.0, 0.0, 0.2, 1) forwards',
        'glow': 'glow 2s ease-in-out infinite',
        'shake': 'shake 500ms ease-in-out',
        'spin': 'spin 1s linear infinite',
        'wiggle': 'wiggle 500ms ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'button-press': 'buttonPress 100ms ease',
        'chat-item-in': 'chatItemIn 300ms ease-out forwards',
        'chat-group-in': 'chatGroupIn 200ms ease-out forwards',
        'action-btn-in': 'actionBtnIn 150ms ease-out forwards',
      },
      keyframes: {
        messageIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInTop: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInBottom: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideOutLeft: {
          '0%': { opacity: '1', transform: 'translateX(0)' },
          '100%': { opacity: '0', transform: 'translateX(-20px)' },
        },
        slideOutRight: {
          '0%': { opacity: '1', transform: 'translateX(0)' },
          '100%': { opacity: '0', transform: 'translateX(20px)' },
        },
        slideOutTop: {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(-20px)' },
        },
        slideOutBottom: {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(20px)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        scaleOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0.95)' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { opacity: '1', transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        bounce: {
          '0%, 100%': { transform: 'translateY(0)' },
          '25%': { transform: 'translateY(-10px)' },
          '50%': { transform: 'translateY(0)' },
          '75%': { transform: 'translateY(-5px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 5px rgba(59, 130, 246, 0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.6), 0 0 30px rgba(59, 130, 246, 0.3)' },
        },
        typingDot: {
          '0%, 100%': { transform: 'translateY(0)', opacity: '0.4' },
          '25%': { transform: 'translateY(-6px)', opacity: '1' },
          '50%': { transform: 'translateY(0)', opacity: '0.4' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '0.5' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 5px rgba(59, 130, 246, 0.5)' },
          '50%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.8), 0 0 30px rgba(59, 130, 246, 0.4)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
        },
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        buttonPress: {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(0.95)' },
        },
        chatItemIn: {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        chatGroupIn: {
          '0%': { opacity: '0', transform: 'translateY(-4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        actionBtnIn: {
          '0%': { opacity: '0', transform: 'scale(0.8)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      transitionDuration: {
        '0': '0ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
      transitionTimingFunction: {
        'standard': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
        'decelerate': 'cubic-bezier(0.0, 0.0, 0.2, 1)',
        'accelerate': 'cubic-bezier(0.4, 0.0, 1, 1)',
        'sharp': 'cubic-bezier(0.4, 0.0, 0.6, 1)',
        'emphasized': 'cubic-bezier(0.2, 0.0, 0, 1)',
        'emphasized-decelerate': 'cubic-bezier(0.05, 0.7, 0.1, 1)',
        'emphasized-accelerate': 'cubic-bezier(0.3, 0.0, 0.8, 0.15)',
        'spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
    },
  },
  plugins: [],
}
