import test, { after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import { build } from 'esbuild';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..'), win=new Window({url:'http://localhost/'});
Object.assign(globalThis,{window:win,document:win.document,HTMLElement:win.HTMLElement,Node:win.Node,Element:win.Element,requestAnimationFrame:fn=>setTimeout(fn,0),cancelAnimationFrame:clearTimeout,IS_REACT_ACT_ENVIRONMENT:true});
Object.defineProperty(globalThis,'navigator',{value:win.navigator,configurable:true});
win.HTMLElement.prototype.scrollIntoView=()=>{};
class Channel {port1={onmessage:null};port2={postMessage:()=>setTimeout(()=>this.port1.onmessage?.(),0)};}
Object.defineProperty(globalThis,'MessageChannel',{value:Channel,configurable:true});
const state=globalThis.__agentSuggestionsTest={};
const bundle=await build({stdin:{contents:`import {createRoot} from 'react-dom/client'; import {act,StrictMode} from 'react'; import {AgentChatView} from './src/components/Layout/AgentChatView'; export {act}; export async function render(container,id='a',existing,strict=false){const root=existing||createRoot(container);await act(async()=>root.render(strict?<StrictMode><AgentChatView agentId={id} onBack={()=>{}}/></StrictMode>:<AgentChatView agentId={id} onBack={()=>{}}/>));return root;}`,resolveDir:root,sourcefile:'agent-suggestions.tsx',loader:'tsx'},bundle:true,format:'esm',platform:'browser',jsx:'automatic',write:false,plugins:[{name:'test-fixtures',setup(build){
 build.onResolve({filter:/stores\/agentsStore$/},()=>({path:'store',namespace:'fixture'}));
 build.onResolve({filter:/^framer-motion$/},()=>({path:'motion',namespace:'fixture'}));
 build.onLoad({filter:/.*/,namespace:'fixture'},({path})=>({loader:'js',resolveDir:root,contents:path==='store'?`export const useAgentsStore=selector=>selector(globalThis.__agentSuggestionsTest.store);`:`import React from 'react';const C=React.forwardRef(({children,initial,animate,exit,transition,...props},ref)=>React.createElement('div',{...props,ref},children));const B=React.forwardRef(({children,initial,animate,exit,transition,...props},ref)=>React.createElement('button',{...props,ref},children));export const motion={div:C,button:B};export const AnimatePresence=({children})=>children;`}));
}}]});
const {act,render}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
let container,mounted;
const agent=id=>({id,name:'Synthetic '+id,description:'写作助手',opening_message:'Synthetic greeting',enable_suggestions:true,created_at:'2026-10-08T00:00:00Z'});
const pending=()=>container.textContent.includes('生成建议中...');
const button=text=>[...container.querySelectorAll('button')].find(b=>b.textContent.trim()===text);
async function complete(index,values){await act(async()=>state.calls[index].resolve(values));}
async function update(){mounted=await render(container,state.store.currentAgent.id,mounted);}
beforeEach(async()=>{if(mounted)await act(async()=>mounted.unmount());container?.remove();container=document.createElement('div');document.body.append(container);mounted=null;state.calls=[];state.store={agents:[agent('a'),agent('b')],currentAgent:agent('a'),agentMessages:new Map([['a',[]],['b',[]]]),selectAgent:()=>{},fetchAgentMessages:async()=>{},sendAgentMessage:async()=>{},fetchAgentSuggestions:id=>new Promise((resolve,reject)=>state.calls.push({id,resolve,reject}))};});
after(async()=>{if(mounted)await act(async()=>mounted.unmount());win.close();});
test('valid deferred nonempty suggestions settle instead of cancelling their own loading state',async()=>{mounted=await render(container);assert.equal(state.calls.length,1);assert.equal(pending(),true);await complete(0,['Synthetic valid suggestion']);assert.equal(pending(),false);assert.ok(button('Synthetic valid suggestion'));assert.equal(state.calls.length,1);});
test('empty suggestions settle using existing local fallback without redispatch',async()=>{mounted=await render(container);await complete(0,[]);assert.equal(pending(),false);assert.ok(button('帮我写一篇关于这个主题的文章'));assert.equal(state.calls.length,1);});
test('rejected suggestion request settles using existing fallback',async()=>{mounted=await render(container);await act(async()=>state.calls[0].reject(new Error('synthetic failure')));assert.equal(pending(),false);assert.ok(button('给我一些创意灵感和方向'));assert.equal(state.calls.length,1);});
test('explicit initial refresh starts exactly one new request',async()=>{mounted=await render(container);await complete(0,['First fixture suggestion']);await act(async()=>button('换一批').click());assert.equal(state.calls.length,2);assert.equal(pending(),true);await complete(1,['Refreshed fixture suggestion']);assert.equal(pending(),false);assert.ok(button('Refreshed fixture suggestion'));assert.equal(button('First fixture suggestion'),undefined);});
test('newer completed chat ignores old response while its own suggestions are pending',async()=>{mounted=await render(container);state.store.agentMessages.set('a',[{id:'new-message',agent_id:'a',sender_type:'agent',content:'Synthetic answer',created_at:'2026-10-08T00:00:01Z'}]);await update();assert.equal(state.calls.length,2);await complete(0,['Stale initial suggestion']);assert.equal(button('Stale initial suggestion'),undefined);assert.equal(pending(),true);await complete(1,['Current message suggestion']);assert.equal(pending(),false);assert.ok(button('Current message suggestion'));});
test('agent switch ignores stale response without clearing newer loading state',async()=>{mounted=await render(container);state.store.currentAgent=state.store.agents[1];await update();assert.deepEqual(state.calls.map(c=>c.id),['a','b']);await complete(0,['Wrong agent suggestion']);assert.equal(button('Wrong agent suggestion'),undefined);assert.equal(pending(),true);await complete(1,['Correct agent suggestion']);assert.equal(pending(),false);assert.ok(button('Correct agent suggestion'));});
test('unmount discards in-flight result',async()=>{mounted=await render(container);await act(async()=>mounted.unmount());mounted=null;await complete(0,['After unmount']);assert.equal(container.textContent,'');assert.equal(state.calls.length,1);});
test('StrictMode effect replay does not duplicate suggestion dispatch',async()=>{mounted=await render(container,'a',undefined,true);assert.equal(state.calls.length,1);await complete(0,['Strict fixture suggestion']);assert.equal(pending(),false);assert.ok(button('Strict fixture suggestion'));assert.equal(state.calls.length,1);});
test('streaming and disabled suggestions do not dispatch, completed message does',async()=>{state.store.agentMessages.set('a',[{id:'stream',agent_id:'a',sender_type:'agent',content:'Partial',is_streaming:true,created_at:'2026-10-08T00:00:01Z'}]);mounted=await render(container);assert.equal(state.calls.length,0);state.store.agentMessages.set('a',[{id:'stream',agent_id:'a',sender_type:'agent',content:'Complete',is_streaming:false,created_at:'2026-10-08T00:00:01Z'}]);await update();assert.equal(state.calls.length,1);state.store.currentAgent={...state.store.currentAgent,enable_suggestions:false};await update();await complete(0,['Disabled late suggestion']);assert.equal(pending(),false);assert.equal(button('Disabled late suggestion'),undefined);});
