import test,{beforeEach,after}from'node:test';import assert from'node:assert/strict';import{Window}from'happy-dom';import{build}from'esbuild';import{resolve}from'node:path';
const root=resolve(import.meta.dirname,'..'),window=new Window({url:'https://qunthink.test'});Object.assign(globalThis,{window,document:window.document,localStorage:window.localStorage,HTMLElement:window.HTMLElement,Node:window.Node,Element:window.Element,requestAnimationFrame:fn=>setTimeout(fn,0),IS_REACT_ACT_ENVIRONMENT:true});Object.defineProperty(globalThis,'navigator',{value:window.navigator,configurable:true});class Channel{port1={onmessage:null};port2={postMessage:()=>setTimeout(()=>this.port1.onmessage?.(),0)}};Object.defineProperty(globalThis,'MessageChannel',{value:Channel,configurable:true});globalThis.__writing={};
const built=await build({stdin:{resolveDir:root,loader:'tsx',contents:`import{createRoot}from'react-dom/client';import{act}from'react';import{ConversationWriting}from'./src/components/Writing/ConversationWriting';import{useTasksStore}from'./src/stores/tasksStore';import{useTaskResultsStore}from'./src/stores/taskResultsStore';export{act,useTasksStore,useTaskResultsStore};export async function mount(el){const root=createRoot(el);await act(async()=>root.render(<ConversationWriting groupId="group-1"><div>原会话内容</div></ConversationWriting>));return root;}`},bundle:true,write:false,format:'esm',platform:'browser',jsx:'automatic',plugins:[{name:'writing-ui',setup(build){const routes=[[/services\/api$/,'api'],[/(?:utils\/|\.\/)cacheUtils$/,'cache'],[/(?:stores\/|\.\/)modelsStore$/,'models'],[/stores\/groupsStore$/,'groups'],[/stores\/messagesStore$/,'messages'],[/\.\/TaskResultEditor$/,'editor']];for(const[filter,path]of routes)build.onResolve({filter},()=>({path,namespace:'mock'}));build.onLoad({filter:/.*/,namespace:'mock'},({path})=>({loader:'tsx',resolveDir:root,contents:{api:`export const getAuthGeneration=()=>1;export const axiosInstance={get:async path=>({data:path==='/tasks'?globalThis.__writing.tasks:globalThis.__writing.document}),post:(...args)=>globalThis.__writing.post(...args),patch:async()=>({data:{}}),delete:async()=>({data:{}})};`,cache:`export const getCacheUserId=()=> 'alice';`,models:`export const requestError=error=>error.message;`,groups:`export const useGroupsStore=fn=>fn({groups:[{id:'group-1',name:'读书活动',space_category:'social'}]});`,messages:`export const useMessagesStore=fn=>fn({messages:{'group-1':globalThis.__writing.messages}});`,editor:`export const TaskResultEditor=({taskId})=><div data-task-id={taskId}>打开同一份正文</div>;`}[path]}))}}]});
const{act,mount,useTasksStore:tasks,useTaskResultsStore:results}=await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`);let container,mounted;const source={id:'message-20',group_id:'group-1',sender_type:'user',content:'明确改到10月20日。材料 https:&#x2F;&#x2F;example.test',edited_at:'2026-10-03T11:00:00Z'};
const flush=()=>new Promise(resolve=>setTimeout(resolve,0));const waitFor=async check=>{for(let n=0;n<200&&!check();n++)await new Promise(resolve=>setTimeout(resolve,5));assert.ok(check(),'expected the prepared request to reach the mock transport');};const button=text=>[...container.querySelectorAll('button')].find(el=>el.textContent===text);async function type(el,value){await act(async()=>{Object.getOwnPropertyDescriptor(el.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:window.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new window.Event('input',{bubbles:true}))})}
beforeEach(async()=>{if(mounted)await act(async()=>mounted.unmount());container?.remove();localStorage.clear();tasks.getState().cleanup();results.getState().cleanup();globalThis.__writing={tasks:[],messages:[source],post:async()=>({data:{}}),document:{task_id:'task-1',revision:0,head_version_id:null,versions:[],source:{status:'current',hash:null,messages:[],missing_message_ids:[]}}};results.getState().openPanel('group-1',undefined,source.id);container=document.createElement('div');document.body.append(container);mounted=await mount(container);await act(async()=>{await flush()})});after(async()=>{if(mounted)await act(async()=>mounted.unmount());window.close()});

test('a message-origin document visibly retains its exact source and creates without a model',async()=>{
 assert.match(container.textContent,/从这条消息开始/);assert.match(container.textContent,/https:\/\/example.test/);assert.match(container.textContent,/最多 40 条/);await type(container.querySelector('input[maxlength="150"]'),'读书活动邀请');await type(container.querySelector('textarea[maxlength="12000"]'),'写给朋友，以明确更正20日为准');let sent;globalThis.__writing.post=async(path,payload)=>{sent={path,payload};const task={...payload,id:'task-1',history:[],result:'',status:'pending'};globalThis.__writing.tasks=[task];return{data:task}};await act(async()=>{button('保存用途，开始写正文').click();await waitFor(()=>sent)});assert.equal(sent.payload.model_id,null);assert.equal(sent.payload.auto_run,false);assert.equal(sent.payload.group_id,'group-1');assert.equal(sent.payload.source_message_id,source.id);assert.equal(sent.payload.source_message_edited_at,source.edited_at);assert.equal(sent.payload.prompt,'写给朋友，以明确更正20日为准');assert.equal(container.querySelector('[data-task-id]').dataset.taskId,'task-1');assert.match(container.textContent,/原会话内容/);
});
test('existing task selection continues the same identity instead of creating an empty workspace',async()=>{
 const task={id:'existing-task',title:'已经改过的邀请',prompt:'检查时间',group_id:'group-1',status:'needs_review',history:[],result:'人工邀请'};globalThis.__writing.tasks=[task];let posts=0;globalThis.__writing.post=async()=>{posts++;return{data:{}}};await act(async()=>tasks.getState().fetch());const entry=[...container.querySelectorAll('button')].find(el=>el.textContent.includes('已经改过的邀请'));await act(async()=>{entry.click();await flush()});assert.equal(container.querySelector('[data-task-id]').dataset.taskId,'existing-task');assert.equal(posts,0);
});
test('unavailable originating message requires explicit switch to conversation-only scope',async()=>{
 globalThis.__writing.messages=[];await act(async()=>tasks.getState().setComposerDraft({...tasks.getState().composerDraft,title:'草稿',prompt:'写邀请',groupId:'group-1'}));assert.match(container.textContent,/原消息暂不可用/);assert.equal(button('保存用途，开始写正文').disabled,true);await act(async()=>button('改为只关联会话近期材料').click());assert.equal(button('保存用途，开始写正文').disabled,false);let sent;globalThis.__writing.post=async(_,payload)=>{sent=payload;const task={...payload,id:'task-1',history:[],result:'',status:'pending'};globalThis.__writing.tasks=[task];return{data:task}};await act(async()=>{button('保存用途，开始写正文').click();await waitFor(()=>sent)});assert.equal(sent.source_message_id,null);
});

test('lost create acknowledgment automatically reopens the same task with clear feedback and one POST',async()=>{
 await type(container.querySelector('input[maxlength="150"]'),'回执恢复邀请');await type(container.querySelector('textarea[maxlength="12000"]'),'检查20日');let posts=0;globalThis.__writing.post=async(_,payload,config)=>{posts++;globalThis.__writing.tasks=[{...payload,id:'task-1',client_request_id:config.headers['Idempotency-Key'],history:[],result:'',status:'pending'}];throw new Error('lost ACK')};await act(async()=>{button('保存用途，开始写正文').click();await waitFor(()=>tasks.getState().recoveredCreate?.taskId==='task-1')});assert.equal(posts,1);assert.match(container.textContent,/已找到上次保存的同一份文稿/);assert.equal(container.querySelector('[data-task-id]').dataset.taskId,'task-1');assert.equal(tasks.getState().composerDraft.prompt,'');assert.equal(tasks.getState().uncertainCreate,false);
});
