import test,{beforeEach,after}from'node:test';
import assert from'node:assert/strict';
import{build}from'esbuild';
import{Window}from'happy-dom';
import{resolve}from'node:path';
const window=new Window({url:'https://qunthink.test/'});Object.assign(globalThis,{window,document:window.document,localStorage:window.localStorage});after(()=>window.close());globalThis.__transportUser='alice';const root=resolve(import.meta.dirname,'..');
const built=await build({stdin:{resolveDir:root,loader:'ts',contents:`export{axiosInstance,confirmAuthIdentity}from'./src/services/api';export{useTaskResultsStore}from'./src/stores/taskResultsStore';export{readTaskReceipts}from'./src/utils/taskRecovery';export{getDiagnosticEvents}from'./src/observability/runtimeDiagnostics';`},bundle:true,write:false,platform:'browser',format:'esm',define:{'import.meta.env.DEV':'false','import.meta.env.VITE_AUTH_MODE':'"session"'},plugins:[{name:'result-transport',setup(build){build.onResolve({filter:/(?:utils\/|\.\/)cacheUtils$/},()=>({path:'cache',namespace:'mock'}));build.onResolve({filter:/\.\/runtimeConfig$/},()=>({path:'runtime',namespace:'mock'}));build.onLoad({filter:/.*/,namespace:'mock'},({path})=>({loader:'js',contents:path==='cache'?`export const getCacheUserId=()=>globalThis.__transportUser;`:`export const getApiBaseUrl=()=>'/api';export const getApiBaseUrlCandidates=()=>['/api'];export const rememberBackendOrigin=()=>{};`}))}}]});
const{axiosInstance,confirmAuthIdentity,useTaskResultsStore:store,readTaskReceipts,getDiagnosticEvents}=await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`);
const version={id:'v1',sequence:1,kind:'manual',parent_version_id:null,run_id:null,content:'邀请正文20日',content_hash:'a'.repeat(64),created_at:'2026-10-04T12:00:00Z',source_hash:'b'.repeat(64),source_messages:[],source_status:'current',content_hidden:false};
const doc=(extra={})=>({task_id:'task-1',title:'邀请',group_id:'group-1',revision:1,head_version_id:'v1',accepted_version_id:null,accepted_content_hash:null,accepted_at:null,versions:[version],source:{status:'current',hash:'b'.repeat(64),messages:[],missing_message_ids:[],message:null},generation:{status:'needs_review',run_id:null,source_input_stale:false},...extra});
function reply(config,status,data){const response={config,status,data,headers:{},statusText:String(status)};return config.validateStatus(status)?Promise.resolve(response):Promise.reject(Object.assign(new Error('adapter-error'),{config,response}));}
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
beforeEach(async()=>{store.getState().cleanup();localStorage.clear();globalThis.__transportUser='alice';confirmAuthIdentity('alice');document.cookie='XSRF-TOKEN=synthetic';axiosInstance.defaults.adapter=config=>reply(config,200,doc());await store.getState().select('task-1')});

test('real Axios timeout sends one POST and query-only recovery keeps the original command/account',async()=>{
 const writes=[],reads=[];let key;axiosInstance.defaults.adapter=config=>{if(config.method==='post'){writes.push(config);key=JSON.parse(config.data).client_request_id;return Promise.reject(Object.assign(new Error('secret-body-must-not-log'),{config,code:'ERR_NETWORK'}))}reads.push(config);return reply(config,200,{receipt:{id:key,task_id:'task-1',operation:'save',version_id:'v2',status:'succeeded'},document:doc({revision:2,head_version_id:'v2',versions:[{...version,id:'v2',content:'人工修订'}]})})};store.getState().edit('task-1','人工修订');await store.getState().save('task-1');assert.equal(writes.length,1);assert.equal(writes[0].headers.get('Idempotency-Key'),key);assert.equal(writes[0].headers.get('X-Expected-User-Id'),'alice');assert.equal(readTaskReceipts()[0].key,key);await store.getState().verify('task-1');assert.equal(writes.length,1);assert.match(reads[0].url,new RegExp(`/result/commands/${key}$`));assert.equal(readTaskReceipts().length,0);assert.doesNotMatch(JSON.stringify(getDiagnosticEvents()),/人工修订|secret-body|task-1/);
});
test('real interceptor preserves revision conflict without leaking server text or erasing manual input',async()=>{
 axiosInstance.defaults.adapter=config=>config.method==='post'?reply(config,409,{code:'RESULT_REVISION_CONFLICT',error:'private upstream body'}):reply(config,200,doc({revision:2,head_version_id:'v2',versions:[{...version,id:'v2',content:'另一设备正文'}]}));store.getState().edit('task-1','不可覆盖的人工输入');await store.getState().save('task-1');assert.equal(store.getState().editors['task-1'].body,'不可覆盖的人工输入');assert.equal(store.getState().editors['task-1'].conflict,true);assert.doesNotMatch(store.getState().errors['task-1'],/private upstream/);
});
test('same-account reauthentication rejects a delayed exact-accept response',async()=>{
 let finish;axiosInstance.defaults.adapter=config=>new Promise(resolve=>{finish=()=>resolve({config,status:200,headers:{},data:{receipt:{id:JSON.parse(config.data).client_request_id,task_id:'task-1',operation:'accept',version_id:'v1',status:'succeeded'},document:doc({revision:2,accepted_version_id:'v1',accepted_content_hash:version.content_hash})}})});const accepting=store.getState().accept('task-1','v1',version.content_hash,version.source_hash);while(!finish)await tick();store.getState().cleanup();confirmAuthIdentity('bob');globalThis.__transportUser='bob';confirmAuthIdentity('alice');globalThis.__transportUser='alice';finish();await accepting;assert.deepEqual(store.getState().documents,{});assert.deepEqual(store.getState().pending,{});
});
test('authentication denial on an unresolved command never discards its recovery identity',async()=>{
 axiosInstance.defaults.adapter=config=>Promise.reject(Object.assign(new Error('lost'),{config,code:'ERR_NETWORK'}));await store.getState().save('task-1');const key=readTaskReceipts()[0].key;axiosInstance.defaults.adapter=config=>reply(config,403,{error:'CSRF unavailable'});await store.getState().retry('task-1');assert.equal(readTaskReceipts()[0].key,key);assert.equal(store.getState().uncertain['task-1'].key,key);
});
